adotPet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('', include('auth_user.urls')),
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
    path('', include('chat.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,)

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/<str:pk>/', views.chatRoom, name="chat"),
    path('send/', views.Send, name="send"),
    path('getMessages/<str:pk>/', views.getMessages, name="getMessages"),
    path('chatsPage/', views.chatsPage, name="chatsPage")
]

store/models.py
from django.db import models
from auth_user.models import Company

from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=150)
    desc = models.CharField(max_length=250)
    value = models.FloatField()
    fk_company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='product')
    category = models.CharField(max_length=50, null=False)
    discount = models.FloatField(null=True, blank=True)
    divided = models.IntegerField()


class ProductImage(models.Model):
    fk_product = models.ForeignKey(Product, related_name='image', on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product_image')

class ShoppingCart(models.Model):
    fk_product = models.ForeignKey(Product, related_name='shoppingCartProduct', on_delete=models.CASCADE)
    fk_user = models.ForeignKey(User, related_name='shoppingCartUser', on_delete=models.CASCADE)
    ammount = models.IntegerField()

class OrderAddress(models.Model):
    city = models.CharField(max_length=90)
    road = models.CharField(max_length=125)
    number = models.IntegerField()
    complement = models.CharField(max_length=120)

class OrderIten(models.Model):
    fk_product = models.ForeignKey(Product, related_name='orderItemProduct', on_delete=models.CASCADE)
    fk_address = models.ForeignKey(OrderAddress, related_name='orderAddress', on_delete=models.CASCADE, default=None)
    fk_user = models.ForeignKey(User, related_name='productOrderClient', on_delete=models.CASCADE, default=None)
    accepted = models.BooleanField(default=False)
    sent = models.BooleanField(default=False)
    ammount = models.IntegerField()
    dt_sent = models.DateTimeField(default=None, null=True, blank=True)

auth_user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import NumberInput, FileInput
from .models import *


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label='E-mail',
        widget = forms.TextInput(attrs={'class': 'px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': 'Email'}))
    
    nome = forms.CharField(
        required=True,
        label='Nome completo',
        widget = forms.TextInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': 'Nome completo'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'minlength':'8'}))

    class Meta:
        model = User
        fields = ['nome', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.nome = self.cleaned_data['nome']
        if commit:
            user.save()
        return user

    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        if not nome:
            raise forms.ValidationError('Por favor, informe seu nome completo.')
        return nome

class DefaultUserForm(forms.ModelForm):
    telephone = forms.CharField(
        label = 'Telefone',
        widget = forms.NumberInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': '88999999999'}))
    
    class Meta:
        model = DefaultUser
        fields = '__all__'
        exclude = ('fk_user',)

class ProfileImageForm(forms.ModelForm):
    img = forms.ImageField(
        label='',
        widget= FileInput(attrs={'accept':'.jpg, .png','class':'none'}),
        required=False
    )

    class Meta:
        model = ProfileImage
        fields = '__all__'
        exclude = ('fk_user',)

class AddressForm(forms.ModelForm):
    cep = forms.IntegerField(
        label = 'CEP',
        widget = forms.NumberInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': '00000-000'})
    )
    city = forms.CharField(
        label= 'Cidade',
        widget = forms.TextInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': 'Digite o nome da sua cidade'})
    )
    road = forms.CharField(
        label= 'Rua',
        widget = forms.TextInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': 'Informe a sua rua'})
    )
    number = forms.IntegerField(
        label='Número',
        widget = forms.NumberInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': '0000'})
    )

    class Meta:
        model = Address
        fields = '__all__'
        exclude = ('fk_user',)

class CompanyForm(forms.ModelForm):
    social_name = forms.CharField(
        label='Nome Social',
        widget = forms.TextInput(attrs={'class': 'px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': 'Nome Social'})
    )
    fantasy_name = forms.CharField(
        label='Nome Fantasia',
        widget = forms.TextInput(attrs={'class': 'px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': 'Nome Fantasia'})
    )
    cnpj = forms.IntegerField(
        label='CNPJ',
        widget = forms.NumberInput(attrs={'class': 'px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': '00.000.000/0000-00'})
    )
    telephone = forms.CharField(
        label = 'Telefone',
        widget = forms.NumberInput(attrs={'class': 'none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm', 'placeholder': '88999999999'}))
    class Meta:
        model = Company
        fields = '__all__'
        exclude = ('fk_user',)

pages/forms.py
from . import models
from django import forms
from .models import *



choices = [('M', 'Masculino'), ('F', 'Feminino')]
choicesBreed = [
    ('Pug', 'Pug'),
    ('Shih Tzu', 'Shih Tzu'),
    ('Buldogue', 'Buldogue'),
    ('Pastor Alemão', 'Pastor Alemão'),
    ('Poodle', 'Poodle'),
    ('Rottweiler', 'Rottweiler'),
    ('Labrador', 'Labrador'),
    ('Pinscher', 'Pinscher'),
    ('Golden Retriever', 'Golden Retriever'),
    ('Caramelo', 'Caramelo')]

choicesSex = [
    ('Macho', 'Macho'),
    ('Fêmea', 'Fêmea')
]

class RegisterPetForm(forms.ModelForm):
    name = forms.CharField(label='Nome do seu Pet:', widget=forms.TextInput(attrs={'class':'input-pet-information', 'placeholder':'Digite o nome do pet aqui'}))
    breed = forms.ChoiceField(label='Raça', choices=[('', 'Selecione a Raça')]+choicesBreed, widget=forms.Select(attrs={'class':'input-pet-information'}))
    desc = forms.CharField(label='Descrição do animal:', widget=forms.TextInput(attrs={'class':'input-pet-information', 'placeholder': 'Digite a descrição do pet aqui'}))
    age = forms.IntegerField(label='Idade', widget=forms.NumberInput(attrs={'class':'input-pet-information input-idade', 'placeholder':'Idade em anos'}))
    obs = forms.CharField(label='Observações', widget=forms.TextInput(attrs={'class':'input-pet-information', 'placeholder':'Digite as observações aqui'}))
    sex = forms.ChoiceField(label='Sexo', choices=choicesSex, widget=forms.RadioSelect(attrs={'class':'radio-inputs'}))

    class Meta:
        model = Pet
        fields = ['name', 'desc', 'obs', 'age', 'sex','breed',]

class RegisterImgPet(forms.ModelForm):
    img = forms.ImageField(required=True, label=None)
    class Meta:
        model = ImagePet
        fields = ['img',]

templates/perfil/perfil.html
{% extends '../componentes/base.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" href="{% static 'css/meus_pets.css' %}">
{% endblock %}

{% block content %}

{% for pet in pets%}
    {% include 'componentes/petModal.html' %}
{% endfor %}

{% for pet in pets_fav%}
    {% include 'componentes/petModal.html' %}
{% endfor %}

<form method="post">
    {% csrf_token %}
    {{profileImageForm}}
    <button id="submitImg" type="submit" class="none"></button>
</form>

<main class="pets-section Mypets">
    <section class="perfil-insight-information">
        <img src="{% static 'imgs/backgroundPerfilPage.jpg' %}" alt="background img" class="background-perfil">
        <div class="photo-container">
            {% if  info.profileImage.img %}
                <label for="id_img"><img src="{{info.profileImage.img.url}}" alt="imagem do perfil do usuário" class="perfil-photo"></label>
                
            {% else %}
                <img class="buttonPerfil null" src="{% static 'imgs/perfil.svg' %}" alt="">
            {% endif %}
            <h1 class="username">{{info.user}}</h1>
            <span class="usertype">Cadastro de Pessoa</span>
        </div>
        <div class="insights-container">
            <div class="perfil-insight">{{info.petsCount}} <span class="insight-label">Pets</span></div>
            <div class="perfil-insight">{{info.adoptedPets}} <span class="insight-label">Adotados</span></div>
            <div class="perfil-insight">{{info.favoritePets}} <span class="insight-label">Favoritos</span></div>
        </div>
    </section>
    <form method="post" class="perfil-information-container">
        {% csrf_token %}
        <div>
            <article class="card_edit">
                <div>
                    <div class="infos">
                        <label for="name">Nome</label>
                        <p>{{info.user}}</p>
                        <input type="text" name="name" class="none px-3 py-2 w-100 border-radius-inputs border fs-inputs shadow-sm" id="name" value="{{info.user.username}}">
                    </div>
                </div>

                <img class="btnEdit" src="{% static 'imgs/edit.svg' %}" alt="">
                <div class="none buttons">
                    <img class="fechar" onclick="fechar()" src="{% static 'imgs/x.svg' %}" alt="">
                    <button name="editName" type="submit"><img src="{% static 'imgs/ok.svg' %}" alt=""></button>
                </div>
            </article>


            <article class="card_edit">
                <div>
                    <div>
                        <label for="id_telephone">Telefone</label>
                        <p>{{info.defaultUser.telephone}}</p>
                        {{defaultUserForm.telephone}}
                    </div>
                </div>

                <img class="btnEdit" src="{% static 'imgs/edit.svg' %}" alt="">
                <div class="none buttons">
                    <img class="fechar" onclick="fechar()" src="{% static 'imgs/x.svg' %}" alt="">
                    <button type="submit"><img src="{% static 'imgs/ok.svg' %}" alt=""></button>
                </div>
            </article>


            <article class="card_edit">
                <div>
                    <div>
                        <label for="id_cep">Cep</label>
                        <p>{{info.address.cep}}</p>
                        {{addressForm.cep}}
                    </div>
                </div>

                <img class="btnEdit" src="{% static 'imgs/edit.svg' %}" alt="">
                <div class="none buttons">
                    <img class="fechar" onclick="fechar()" src="{% static 'imgs/x.svg' %}" alt="">
                    <button type="submit"><img src="{% static 'imgs/ok.svg' %}" alt=""></button>
                </div>
            </article>
        </div>

        <div>
            <article class="card_edit">
                <div>
                    <div>
                        <label for="id_city">Cidade</label>
                        <p>{{info.address.city}}</p>
                        {{addressForm.city}}
                    </div>
                </div>

                <img class="btnEdit" src="{% static 'imgs/edit.svg' %}" alt="">

                <div class="none buttons">
                    <img class="fechar" onclick="fechar()" src="{% static 'imgs/x.svg' %}" alt="">
                    <button type="submit"><img src="{% static 'imgs/ok.svg' %}" alt=""></button>
                </div>
            </article>

            
            <article class="card_edit">
                <div>
                    <div>
                        <label for="id_road">Rua</label>
                        <p>{{info.address.road}}</p>
                        {{addressForm.road}}
                    </div>
                    
                </div>

                <img class="btnEdit" src="{% static 'imgs/edit.svg' %}" alt="">
                <div class="none buttons">
                    <img class="fechar" onclick="fechar()" src="{% static 'imgs/x.svg' %}" alt="">
                    <button type="submit"><img src="{% static 'imgs/ok.svg' %}" alt=""></button>
                </div>
            </article>


            <article class="card_edit">
                <div>
                    <div>
                        <label for="id_number">Número</label>
                        <p>{{info.address.number}}</p>
                        {{addressForm.number}}
                    </div>
                    
                </div>

                <img class="btnEdit" src="{% static 'imgs/edit.svg' %}" alt="">
                <div class="none buttons">
                    <img class="fechar" onclick="fechar()" src="{% static 'imgs/x.svg' %}" alt="">
                    <button type="submit"><img src="{% static 'imgs/ok.svg' %}" alt=""></button>
                </div>
            </article>
        </div>
    </form>

    <h1>Meus Pets</h1>

    {% include '../componentes/search.html' %}

    <h4>Meus Pets</h4>
    <article class="my-pets">
        {% for pet in pets %}
            {% include 'componentes/petCard.html' %}
        {% endfor %}
    </article>


    <h4>Favoritos</h4>
    <article class="my-pets">
        {% for pet in pets_fav %}
            {% include 'componentes/petCard.html' %}
        {% endfor %}
    </article>
    {% include 'componentes/paginator.html' %}
</main>

<section class="mid-3">
    <div class="mid-3-1">
        <img src="{% static 'imgs/geometryShapes_background.svg' %}" alt="background shapes" class="background-shapes">
        <div class="description-mid-3-1">
            <h3>Faça igual a eles vire um parceiro da AdotePet</h3>
            <button class="parceiro">Seja um Parceiro</button>
        </div>
    </div>
</section>


<script src="{% static 'js/modalPet.js' %}"></script>

<script>
    var form = document.querySelector(".perfil-information-container")
    
    form.addEventListener("click",  function(event){
        var button = event.target
        if(button.classList.contains("btnEdit")){
            var parente = button.parentNode
            var inputElement = parente.querySelector('div div input');
            var paragrafo = parente.querySelector('div div p');
            var imgEdit = parente.querySelector('div img')
            var buttons = parente.querySelector('div .buttons')

            buttons.classList.remove('none')
            imgEdit.classList.add('none')
            paragrafo.classList.add('none')
            inputElement.classList.remove('none')
        }
        else if(button.classList.contains("fechar")){
            var parente = button.parentNode.parentNode
            var inputElement = parente.querySelector('div div input');
            var paragrafo = parente.querySelector('div div p');
            var imgEdit = parente.querySelector('div img')
            var buttons = parente.querySelector('div .buttons')

            buttons.classList.add('none')
            imgEdit.classList.remove('none')
            paragrafo.classList.remove('none')
            inputElement.classList.add('none')
        }
    })


    function fechar(elemento){
        elemento.classList.add('none')
    }
</script>
{% endblock %}